### ISSUE TITLE
Track covers in Windows players

### ISSUE THREAD

**Issue by donelofficial** [YasogaN/WebNowPlaying-RPC#1]
Track covers are not shown in Discord when using a player running in Windows.

**Comment by YasogaN** [comment]
Hi @donelofficial, 
I'll take a look into in a bit and let you know

Sorry for the late reply: i got wrapped up in some coursework

**Comment by YasogaN** [comment]
Hi @donelofficial,
I took look into this and as it appears, the reason i made the program to not show the thumbnails when the player is a desktop application is because, the WebNowPlaying Extension returns a local address for the picture. As Discord doesn't have access to the local address, I made the program in a way so it will show the Windows 11 Logo. 

The only feasible option would be running a tunnel from listening on port 6867. However from a security standpoint, it is inadvisable.

If you have any more questions or facing any more issues I would be happy to answer them and/or provide solutions.
